### ISSUE TITLE
How to handle handlers?

### ISSUE THREAD

**Issue by spencermathews** [conda-forge/pydap-feedstock#13]
Pydap is almost useless without [handlers](http://pydap.org/en/latest/handlers.html). This seems a questionable design decision, but that's a matter for the pydap developers. Since conda-forge only packages pydap itself it's rather unclear how to approach installing them. It seems strange to install the handlers from PyPI after installing the pydap package itself from conda-forge. Perhaps handlers themselves could be included in the conda-forge package? Please advise.

**Comment by ocefpaf** [comment]
You can submit packages for the handles, [see our docs](https://github.com/conda-forge/staged-recipes#getting-started) on how to do that.
