### ISSUE TITLE
Can't import beautifulsoup4

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/pydap-feedstock#23]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

With version 3.5.1 the server dependencies have been commented out in meta.yaml. What is the canonical way to install pydap for server including the needed dependencies? Thanks.

```
/home/runner/micromamba/envs/tests/lib/python3.12/site-packages/pydap/cas/urs.py:1: in <module>
    from . import get_cookies
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    import copy
    import warnings
    
    import requests
>   from bs4 import BeautifulSoup
E   ModuleNotFoundError: No module named 'bs4'

/home/runner/micromamba/envs/tests/lib/python3.12/site-packages/pydap/cas/get_cookies.py:5: ModuleNotFoundError
```

### Installed packages

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
aiobotocore               2.15.1             pyhd8ed1ab_0    conda-forge
aiohappyeyeballs          2.4.3              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.10         py312h178313f_0    conda-forge
aioitertools              0.12.0             pyhd8ed1ab_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
array-api-strict          2.1                pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.31               hcdce11a_5    conda-forge
aws-c-cal                 0.7.4                hd3f4568_4    conda-forge
aws-c-common              0.9.31               hb9d3cd8_0    conda-forge
aws-c-compression         0.2.19               hf20e7d7_4    conda-forge
aws-c-event-stream        0.5.0                h72d8268_0    conda-forge
aws-c-http                0.8.10               h6bb76cc_5    conda-forge
aws-c-io                  0.14.20              h389d861_2    conda-forge
aws-c-mqtt                0.10.7               had056f2_5    conda-forge
aws-c-s3                  0.7.0                hc85afc5_0    conda-forge
aws-c-sdkutils            0.1.19               hf20e7d7_6    conda-forge
aws-checksums             0.1.20               hf20e7d7_3    conda-forge
aws-crt-cpp               0.29.0               h07ed512_0    conda-forge
aws-sdk-cpp               1.11.407             h9c41b47_6    conda-forge
azure-core-cpp            1.14.0               h5cfcd09_0    conda-forge
azure-identity-cpp        1.10.0               h113e628_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h3cf044e_1    conda-forge
azure-storage-common-cpp  12.8.0               h736e048_1    conda-forge
azure-storage-files-datalake-cpp 12.12.0              ha633028_1    conda-forge
backports.zoneinfo        0.2.1           py312h7900ff3_9    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
boto3                     1.35.23            pyhd8ed1ab_0    conda-forge
botocore                  1.35.23         pyge310_1234567_0    conda-forge
bottleneck                1.4.2           py312hc0a28a1_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cartopy                   0.24.0          py312hf9745cd_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cf-units                  3.3.0           py312hc0a28a1_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cftime                    1.6.4           py312hc0a28a1_1    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.9.2          py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.9.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.4.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.11.0             pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py312h68727a3_2    conda-forge
coverage                  7.6.4           py312h178313f_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   1.0.0           py312h66e93f0_1    conda-forge
dask-core                 2024.10.0          pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.16             pyhd8ed1ab_0    conda-forge
distlib                   0.3.9              pyhd8ed1ab_0    conda-forge
distributed               2024.10.0          pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
docopt-ng                 0.9.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
execnet                   2.1.1              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
flox                      0.9.12             pyhd8ed1ab_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
fonttools                 4.54.1          py312h178313f_1    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
frozendict                2.4.6           py312h66e93f0_0    conda-forge
frozenlist                1.5.0           py312h66e93f0_0    conda-forge
fsspec                    2024.10.0          pyhff2d567_0    conda-forge
geos                      3.13.0               h5888daf_0    conda-forge
geotiff                   1.7.3                h77b800c_3    conda-forge
gflags                    2.2.2             h5888daf_1005    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5netcdf                  1.4.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          nompi_py312hedeef09_102    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hypothesis                6.116.0            pyha770c72_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
identify                  2.6.1              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
iris                      3.9.0              pyha770c72_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
json-c                    0.18                 h6688a6e_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py312h68727a3_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
legacy-cgi                2.6.1              pyh5b84bb0_3    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libarrow                  18.0.0           ha5db6c2_0_cpu    conda-forge
libarrow-acero            18.0.0           h5888daf_0_cpu    conda-forge
libarrow-dataset          18.0.0           h5888daf_0_cpu    conda-forge
libarrow-substrait        18.0.0           he882d9a_0_cpu    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgdal-core              3.9.3                hd5b9bfb_2    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgoogle-cloud           2.30.0               h438788a_0    conda-forge
libgoogle-cloud-storage   2.30.0               h0121fbd_0    conda-forge
libgrpc                   1.65.5               hf5c653b_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hf539b9f_1021    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libmamba                  1.5.10               hf72d635_1    conda-forge
libmambapy                1.5.10          py312hf3f0a4e_1    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_0    conda-forge
libparquet                18.0.0           h6bd9018_0_cpu    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libprotobuf               5.27.5               h5b01275_2    conda-forge
libre2-11                 2024.07.02           hbbce691_1    conda-forge
librttopo                 1.1.0               h97f6797_17    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libspatialite             5.1.0               h1b4f908_11    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libthrift                 0.21.0               h0e7cc3e_0    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libudunits2               2.2.28               h40f5838_3    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.4               hb346dea_2    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzip                    1.11.2               h6991a6a_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
llvmlite                  0.43.0          py312h374181b_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      5.3.0           py312he28fd5a_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
markupsafe                3.0.2           py312h178313f_0    conda-forge
matplotlib-base           3.9.2           py312hd3ec401_1    conda-forge
menuinst                  2.1.2           py312h7900ff3_1    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
msgpack-python            1.1.0           py312h68727a3_0    conda-forge
multidict                 6.1.0           py312h178313f_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nc-time-axis              1.4.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
netcdf4                   1.7.1           nompi_py312h21d6d8e_102    conda-forge
nodeenv                   1.9.1              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numba                     0.60.0          py312h83e6fd3_0    conda-forge
numbagg                   0.8.2              pyhd8ed1ab_0    conda-forge
numcodecs                 0.13.1          py312hf9745cd_0    conda-forge
numexpr                   2.10.1          py312h6a710ac_103    conda-forge
numpy                     2.0.2           py312h58c1407_0    conda-forge
numpy_groupies            0.11.2             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
opt_einsum                3.4.0              pyhd8ed1ab_0    conda-forge
orc                       2.0.2                h690cf93_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hf9745cd_1    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    11.0.0          py312h7b63e92_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pooch                     1.8.2              pyhd8ed1ab_0    conda-forge
pre-commit                4.0.1              pyha770c72_0    conda-forge
proj                      9.5.0                h12925eb_0    conda-forge
propcache                 0.2.0           py312h66e93f0_2    conda-forge
psutil                    6.1.0           py312h66e93f0_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pyarrow                   18.0.0          py312h9cebb41_0    conda-forge
pyarrow-core              18.0.0          py312h01725c0_0_cpu    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312h98912ed_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydap                     3.5.1              pyhd8ed1ab_0    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyproj                    3.7.0           py312he630544_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.3.3              pyhd8ed1ab_0    conda-forge
pytest-cov                6.0.0              pyhd8ed1ab_0    conda-forge
pytest-env                1.1.5              pyhd8ed1ab_0    conda-forge
pytest-github-actions-annotate-failures 0.2.0                    pypi_0    pypi
pytest-timeout            2.3.1              pyhd8ed1ab_1    conda-forge
pytest-xdist              3.6.1              pyhd8ed1ab_0    conda-forge
python                    3.12.7          hc5c86c4_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python-xxhash             3.5.0           py312h66e93f0_1    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h66e93f0_1    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
rasterio                  1.4.2           py312h8456570_0    conda-forge
re2                       2024.07.02           h77b4e00_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6          py312h66e93f0_1    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
s2n                       1.5.5                h3931f03_0    conda-forge
s3transfer                0.10.3             pyhd8ed1ab_0    conda-forge
scipy                     1.14.1          py312h62794b6_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.6           py312h391bc85_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
snuggs                    1.4.7              pyhd8ed1ab_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.15.4             pyh267e887_1    conda-forge
sqlite                    3.47.0               h9eae976_1    conda-forge
statsmodels               0.14.4          py312hc0a28a1_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
toolz                     1.0.0              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h66e93f0_1    conda-forge
tqdm                      4.66.6             pyhd8ed1ab_0    conda-forge
truststore                0.10.0             pyhd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
udunits2                  2.2.28               h40f5838_3    conda-forge
ukkonen                   1.0.1           py312h68727a3_5    conda-forge
unicodedata2              15.1.0          py312h66e93f0_1    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
virtualenv                20.27.1            pyhd8ed1ab_0    conda-forge
webob                     1.8.9              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py312h66e93f0_1    conda-forge
xarray                    2024.10.1.dev13+g638b15f5          pypi_0    pypi
xerces-c                  3.2.5                h988505b_2    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xxhash                    0.8.2                hd590300_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
yarl                      1.16.0          py312h66e93f0_0    conda-forge
zarr                      2.18.3             pyhd8ed1ab_0    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

### Environment info

     active environment : base
    active env location : /home/runner/micromamba/envs/tests
            shell level : 1
       user config file : /home/runner/.condarc
 populated config files : /home/runner/work/_temp/setup-micromamba/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.9.2=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/runner/micromamba/envs/tests  (writable)
      conda av data dir : /home/runner/micromamba/envs/tests/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/runner/micromamba/envs/tests/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /home/runner/micromamba/envs/tests/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Linux/6.5.0-1025-azure ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.10
                UID:GID : 1001:127
             netrc file : None
           offline mode : False

**Comment by Mikejmnez** [comment]
Thanks for reaching out @kmuehlbauer ! I am working on updating the documentation for pydap to better describe the features/additions/subtractions associated with latest version of pydap. 

With the new pydap version, we made the choice to provide a minimal conda/pip installation, taking into consideration that most people use pydap's client and not so much the server version (btw: pydap's server badly needs an upgrade!). As a result, to install `pydap` to be able to use it as a server, you need to do the following:

```python
pip install pydap"[server,netcdf]"
```
That will allow you to install `pydap` (if not already installed) along with the (optional/extra) dependencies to use it as a server. You can see what these extra dependencies are on the pyproject.toml ([extras](https://github.com/pydap/pydap/blob/main/pyproject.toml#L62)) in case you want to defined them on a yaml file used by conda/mamba directly.

There is a bit of this on the documentation (see [HowToInstall](https://pydap.github.io/pydap/how_to_install.html#extra-dependencies
)), but it needs improvement but it is on my todo list for this coming days.

BTW: Would it be possible to share how you are using pydap as a server. I would like to upgrade pydap's server capabilities, and knowledge of how it is being used would help a lot!

**Comment by kmuehlbauer** [comment]
Thanks for the quick and helpful reply @Mikejmnez.

For the documentation page please explicitly add that there is currently no dedicated pydap-server on conda-forge and users should add the needed dependencies by themselves. A careful reader can extract this from the current docs, but an explicit mention would still help.

We (xarray) use the pydap server part to create a server endpoint in our CI tests for testing the client part in our backend code. So I think this is a common use case for packages which normally only use the client.

We've had quite intense discussion over at [xarray-feedstock](https://github.com/conda-forge/xarray-feedstock/pull/113) how the library and it's dependencies should be included in the canocical `xarray` package and what might be moved into something like `xarray-core` or `xarray-minimal`. This is still in the works, though.

Happy shoutout also to @ocefpaf :wave:. Would it make sense to turn this feedstock into a multipackage output with `pydap` (the client), `pydap-server` (the client + server)? I'm not sure what is the best solution for `pydap`, but I think the server part should also be available as package from conda-forge somehow.

**Comment by ocefpaf** [comment]
> Happy shoutout also to [@ocefpaf](https://github.com/ocefpaf) 👋. Would it make sense to turn this feedstock into a multipackage output with `pydap` (the client), `pydap-server` (the client + server)? I'm not sure what is the best solution for `pydap`, but I think the server part should also be available as package from conda-forge somehow.

Yes it does. In fact I wanted to do that but just forgot. I'll try to get to it tomorrow if no one beats me to it.

**Comment by Mikejmnez** [comment]
> For the documentation page please explicitly add that there is currently no dedicated pydap-server on conda-forge and users should add the needed dependencies by themselves. A careful reader can extract this from the current docs, but an explicit mention would still help.

💯  That is the plan so far. It's taken some time to revive this (largely abandoned) package and having a clean and informative documentation is certainly a big part of this goal. 
> We (xarray) use the pydap server part to create a server endpoint in our CI tests for testing the client part in our backend code. So I think this is a common use case for packages which normally only use the client.
> 
👍🏽  Interesting! I knew xarray uses the client (also in need for an upgrade on how it uses pydap), but was not aware of using the server side.  The current `pydap server` is rather fragile and depends on an abandoned project (e.g. `docopt`, although `docopt-ng`  provided a temporary fix. `gunicorn` and `PasteDeploy` also gave some trouble for a while). I am planning on spending some time working on improving pydap's server side to depend instead on `FastApi`. Not sure how much of a project this will become...

> We've had quite intense discussion over at [xarray-feedstock](https://github.com/conda-forge/xarray-feedstock/pull/113) how the library and it's dependencies should be included in the canocical `xarray` package and what might be moved into something like `xarray-core` or `xarray-minimal`. This is still in the works, though.
> 
👍🏽 that makes sense.

> Would it make sense to turn this feedstock into a multipackage output with `pydap` (the client), `pydap-server` (the client + server)? I'm not sure what is the best solution for `pydap`, but I think the server part should also be available as package from conda-forge somehow. 

Hmm. I have to say I have not split a package in the past so I am not very familiar with the consequences to this, and perhaps there is no basis to my concerns. IMHO I am a little wary of splitting this package into more packages. In the past, `pydap` benefited greatly from its flexibility to add extensions/plugins/handlers, but right now all those are essentially abandoned, severely outdated, and thus no longer functional. 
1. What would be your vision for `pydap-server` that cannot be accomplished by adding to a yaml file the 7 extra dependencies that are needed to run pydap's server with conda-forge install? 
2. How would a `pydap-server` integrate the changes, any and when these occur, that I will be making to `pydap` (e.g. bringing FastAPI and potentially others?) 

 To clarify I am not against these changes, but as a maintainer of this package, with ongoing plans to push changes to improve its capabilities (both client and server side), I would like to be kept in the loop. Cheers!

**Comment by kmuehlbauer** [comment]
@Mikejmnez 

Regarding the multi-output, this would be no real split of the upstream pydap, but just another conda-forge package which depends on the main pydap conda-forge package and just adds the server dependencies.

This will work as long the server code is distributed with pydap.

So if you are working on updates of pydap client as well as server, that's great  💯 and I think xarray will take up any changes that are introduced in API as well as dependencies over time.

I think everything what you have in mind in revamping pydap is possible with this feedstock. No need to split pydap itself.

Currently we have added the additional dependencies to our CI environment. But it would be much easier to just install a pydap-server and get the dependencies for free.

Hope that makes sense.

**Comment by Mikejmnez** [comment]
@kmuehlbauer thanks for the explanation - it all makes sense to me.
