### ISSUE TITLE
pydap/pydap-server multioutput broken

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/pydap-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

The new create packages are installing into a `lib/python3.10` folder, although my python is 3.12. 

cc @ocefpaf 

### Installed packages

no item

### Environment info

no item

**Comment by ocefpaf** [comment]
I guess it should not be noarch generic.

**Comment by kmuehlbauer** [comment]
Let's try this

**Comment by kmuehlbauer** [comment]
#26

**Comment by ocefpaf** [comment]
My bad. I should have caught that one. Do you mind sending a PR to mark the first build as broken?

**Comment by kmuehlbauer** [comment]
> Do you mind sending a PR to mark the first build as broken?

Could this also be patched? Otherwise I send in a PR to mark the package as broken.

**Comment by kmuehlbauer** [comment]
https://github.com/conda-forge/admin-requests/pull/1149
