### ISSUE TITLE
build 2 macOS

### ISSUE THREAD

**Issue by bucricket** [conda-forge/pydap-feedstock#7]
Hi I see that you have a new build for pydap.  I'm wondering if you can build it for macOS too.

Thanks!

**Comment by ocefpaf** [comment]
It is building. You can follow the build here: https://travis-ci.org/conda-forge/pydap-feedstock/builds/202561180

`OS X` packages are built on Travis-CI and that is awfully slow.

**Comment by bucricket** [comment]
Great!  One quick question.  The new build does it include the latest merge to the master on pydap git?

Mitch

**Comment by ocefpaf** [comment]
> The new build does it include the latest merge to the master on pydap git?

What merge? Probably not as this is the latest release and not latest `master`. I would request upstream for a new release of there ar any important changes you need.

**Comment by bucricket** [comment]
Ok so this builds are based on releases. That makes sense.  I’m sorry still figuring out this system.

Mitch
